### ISSUE TITLE
Limited IAM profile

### ISSUE THREAD

**Issue by vegardx** [Chialab/aws-autoscaling-gitlab-runner#2]
Hi,

Happen to stumble upon this while searching for ideas of how to do lifecycle management of runners with autoscaling groups. I hope that your'e aware that gitlab-runner will be able to terminate any instance in that VPC, since it can describe all instances and apply tags to any instance in that account. 

I'm currently looking for a solution to this, but have yet to find anything fruitful.

**Comment by fquffio** [comment]
Hi @vegardx ! Thanks for your report. Sorry it took me 4 days to answer, but I didn't read the notification. 😞 

To be honest, I wasn't aware of this security issue. Thanks a lot for your report! I'll investigate this as soon as I can.

Maybe it's possible to restrict `ec2:CreateTags` action with an IAM policy that looks like this:

```json
{
  "Effect": "Allow",
  "Action": [
     "ec2:CreateTags"
  ],
  "Resource": "*",
  "Condition": {
     "StringEquals": {
         "ec2:CreateAction": "RunInstances"
      }
   }
}
```

Hopefully this can be restricted furtherly, but I need to make a couple of tests…

**Comment by vegardx** [comment]
No worries!

I've been scratching my head on possible workarounds as well, but no luck so far. But do keep me posted if you find something, I think a lot of people will find this useful. 

In the mean time I've started working with native ASGs, but that has its own set of challenges that I'm still waiting for a reply from the GitLab people about. Overall it all feels very hackish and I don't really like it.

**Comment by fquffio** [comment]
Working with AWS-native ASGs would be awesome, and it would surely be the most reliable and secure way to run an autoscaling runner. However, there's no out-of-the-box support as far as I know. Perhaps the most elegant ways to achieve this would be a custom GitLab Runner "executor", or a custom Docker Machine "driver".

However, the policy I suggested in my previous comment does not work. 😞 Docker machine does not set tags on the `CreateInstance` API request. For some reason, [tags are set in a second step](https://github.com/docker/machine/blob/master/drivers/amazonec2/amazonec2.go#L752-L757), therefore the `ec2:CreateAction` condition key does not apply. I'm not super-excited with this approach Docker Machine has, as it assumes a lot of permissions are granted to the user/role running Docker Machine. I might try opening a PR to their repo, but I'm not sure it would be accepted (that's how OSS works, of course), and it would quite likely require a lot of time to be released.

For now, I've restricted the IAM policy a bit:
```yaml
Effect: 'Allow'
Action:
  - 'ec2:CreateTags'
Resource:
  - '*'
Condition:
  StringEquals:
    'ec2:Region': !Ref 'AWS::Region'
    'ec2:InstanceType': !Ref 'GitlabRunnerInstanceType'
  StringLike:
    'aws:RequestTag/Name': '*gitlab-docker-machine-*'
```

This doesn't really solve the problem you've been pointing out, but it reduces the blast radius to only the instances of the same type in the same region as your GitLab Runners.

Another possibility would be to assign a "fake" IAM Instance Profile to the runners. The manager policy could be restricted to `RunInstances` only if they have that Instance Profile [because it is set at launch time](https://github.com/docker/machine/blob/master/drivers/amazonec2/amazonec2.go#L719-L721), and to terminate only instances that have that Instance Profile. This feels quite "hacky" to me, but it might work, assuming no one assigns that same profile to other instances.

**Comment by fquffio** [comment]
Hey @vegardx,
yesterday I opened a PR that should hopefully address this issue by assigning an IAM instance profile to the "executor" instances, and limiting the "manager" role to terminate only instances with that profile attached. Yes, I know that in my previous comment I said that it felt quite hacky, and I'm still sticking with that opinion, but it's the best idea I could come up with.

I've updated the stack that runs our company's GitLab runners, and everything's been looking fine for a couple of days now. However, I'd be glad if you had some spare time to review that PR, just in case I missed something — and, as this issue itself testifies, I happen to miss something quite often. 😉 Thanks in advance, and no worries if you can't!

**Comment by vegardx** [comment]
I can't believe I didn't think of that when I started researching it. Not too familiar with stacks, but I don't see obvious problems. Have you tried to just use the aws cli tools on the manager instance to wreck some havoc? 

I have addressed this issue with some architects at GitLab, hopefully they can solve the upstream docker-machine issue of tags being assigned after instance creation. In the current state (at least as documented) I don't feel like they can advertise autoscaling spot instances like they currently are. But your workaround seems like a possible solution.  

Been going down the "native" ASGs route, and it's been working very well so far. But it makes a lot of assumptions based on your load, it's not very dynamic. But I guess that's what we have stacks and terraform for 😅 

Currently I've set up a on-demand autoscaling group, with a minimum of one instance. When we've scaled up to about half of the pool it kicks in another group with spot instances in parallel. But given the limited nature of cloudwatch metric alarms it's hard to make the on-demand instances pause scaling in for a few minutes while we wait to see if there are available spot instances. 

The instances unregister themselves when they receive termination request, but it can be kind of brutal when you lose a spot bid. Failed jobs can linger around for some time due to the timeout. But I'm hoping that some fine tuning of the pipelines can sort that out a little bit. I also have to write some clean up jobs to remove old and offline workers that didn't successfully unregister with gitlab, but so far that has not happened.

**Comment by fquffio** [comment]
> Have you tried to just use the aws cli tools on the manager instance to wreck some havoc?

Yes, and I didn't manage to do anything nasty unless I start assigning that instance profile to other instances by other means — which is something that shouldn't happen under normal circumstances.

> Been going down the "native" ASGs route, and it's been working very well so far. But it makes a lot of assumptions based on your load, it's not very dynamic.

Sounds great! I guess that in most cases work load can be roughly predicted just by scaling out during work hours, and scaling in at nights and in weekends, so as long as the minimum ASG size is being changed accordingly it will be just fine for most companies and teams.

What you've been doing seems awesome… do you plan to release your work as an open source stack/playbook/recipe/template/…? 😃
